In [1]:
import numpy as np

In [12]:
#zadanie 27
a = np.random.randint(-10,10)
b = np.random.randint(-10,10,size=(3,4))

print(a*b)

[[-36  54  48 -30]
 [ 24   0   0  12]
 [-54  36 -36 -24]]


In [15]:
#zadanie 28
c = np.random.randint(-10,10,size=(2,3))
d = np.random.randint(-10,10,size=(3,2))
print(c@d) #mnożenie macierzy

[[-70  -6]
 [-50  -8]]


In [20]:
#zadanie 29
e = np.array([1, 2, 3, 4])
f = np.array([5, 6, 7, 8])
f1 = f.reshape(4,1) 
print(e@f1)

[70]


In [24]:
#zadanie 30
x = np.random.randint(-10,10,size=(2,2))
y = np.random.randint(-10,10,size=(2,2))
z = np.random.randint(-10,10,size=(2,3))
print(x)
print(y)
print(z)
print(x.transpose())
print((x.transpose()-y)@z)

[[ 3  2]
 [-2 -2]]
[[ 9  2]
 [-8 -1]]
[[ -6   8   3]
 [-10   9   7]]
[[ 3 -2]
 [ 2 -2]]
[[ 76 -84 -46]
 [-50  71  23]]
