In [1]:
import numpy as np

In [6]:
#zad 22
m = np.array([
    [1,2,3],  
    [1,2,0],
    [1,0,2]
])
print(m)
print(m[0].sum())
print(m[:,0].sum())
m[0,0]+m[1,1]+m[2,2]

[[1 2 3]
 [1 2 0]
 [1 0 2]]
6
3


5

In [17]:
#zad 23
a = np.array([
    [1,2,3],  
    [1,2,0],
    [1,0,2]
])
b = np.array([
    [5],  
    [5],
    [5]
])
print(a)
print(b)
a1 =np.array([a[0,:]]) #pierwszy rząd z a
b1a =np.array([b[0,:]]) #pojedynczy rząd ,w tym przypadku nawet wyraz
b2a = np.hstack((b1a,b1a,b1a)) #stworzenie poziomej tablicy trzy-elementowej
a2 =np.array([a[2,:]]) #trzeci rząd z a

c = np.vstack((a1,b2a,a2))
print(c)

[[1 2 3]
 [1 2 0]
 [1 0 2]]
[[5]
 [5]
 [5]]
[[1 2 3]
 [5 5 5]
 [1 0 2]]


In [34]:
#zad 24
f = np.array([
    [1,2,3],  
    [1,2,0],
    [1,0,2]
])
g = np.array([
    [5],  
    [5],
    [5]
])
print(f)
print(g)
#f1 =np.array([f[0,:]]).T #pierwszy wiersz zmieniony w kolumnę
f1 =np.array([f[0,1:3]]) #pierwszy rząd, drugi i trzeci wyraz z f
f2a =np.array([f[1,0]]) #drugi rząd, pierwszy wyraz
f2b =np.array([f[1,2]]) #drugi rzad, trzeci wyraz
f3 =np.array([f[2,0:2]])

g1 =np.array([g[0,:]]) #caly rzad
g2 =np.array([g[0,0]]) # tylko jeden wyraz

h1 = np.hstack((g1,f1)) #polozone obok siebie tablice roznoelementowe
h2 = np.hstack((f2a,g2,f2b))
h3 = np.hstack((f3,g1))
h_f = np.vstack((h1,h2,h3))
print(h_f)

[[1 2 3]
 [1 2 0]
 [1 0 2]]
[[5]
 [5]
 [5]]
[[5 2 3]
 [1 5 0]
 [1 0 5]]


In [36]:
#zadanie 25
x = np.matrix([[1,0,1], [2,0,1],[3,0,1]])
print(x)
x.transpose()

[[1 0 1]
 [2 0 1]
 [3 0 1]]


matrix([[1, 2, 3],
        [0, 0, 0],
        [1, 1, 1]])

In [39]:
#zadanie 26
x = np.matrix([[1,0,1], [2,0,1],[3,0,1]])
y = np.matrix([[1,0,1], [2,0,1],[3,0,1]])
if x.transpose()==y:
    print("yes")
else:
    print("no")

<class 'ValueError'>: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()